### ISSUE TITLE
How to extract text from pages

### ISSUE THREAD

**Issue by nartz** [gdelugre/origami#15]
Hi - this is a basic question - but what is the simple way to get the page text? I dont see an example of it and am not seeing an easy way to do that.

Thank you.

**Comment by gdelugre** [comment]
Short answer: this is currently not supported and there is no easy way to do it.

The PDF document contains a set of graphical instructions to render the glyphs on the page at relative or absolute coordinates. In order to reconstruct the text stream, separating the words, the paragraphs and so on. one must be able to parse and interpret the font files (whether they are embedded in the document or installed on the system).

If the properties of every glyph is known (its boxing size, kerning, which unicode character it is mapped to, etc.) it becomes possible to reconstruct the text with a lot of effort still.

However handling the fonts is very complicated. There exist a lot of different font file formats, each with their own set of properties, fonts can be embedded, installed on the system, they can be derived from each other...

In my opinion handling the fonts would require a whole separate library separate from Origami. I would be interested if such a Ruby library existed: something portable across systems and supporting a lot of font formats.

**Comment by bcoles** [comment]
@nartz probably not the answer you're looking for, but the [pdf-reader](https://github.com/yob/pdf-reader) Ruby gem can extract text from a PDF, page by page, with varying levels of success.

As expected, there are some issues. In particular, vertically-aligned text in combination with horizontal text causes some issues. Text aligned using tables can also cause problems.
